services:
  db:
    image: postgres:15
    container_name: biocyclex
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=biocyclex
    ports:
      - "25060:5432"